name: Weather Prediction Model 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    #every 6 hours
    - cron: '0 */6 * * *'

  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - docs/**
      - .github/README.md

  workflow_dispatch: #manal trigger

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Latest Weather Data
        run: python src/fetch_data.py

      - name: Run ETL Pipeline
        run: python src/etl.py

      - name: Run tests
        run: python src/tests.py

      - name: Run Traning Script
        run: python src/train.py

      - name: Verify Model Ouput
        run: ls -R models/

      - name: Commit Trained Model to Repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          git add models/
          git commit -m "Update trained model" || echo "No changes to commit"
          git push